# PostgreSQL'in resmi image'ini kullan
FROM postgres:15

# Postgres şifresini ve veritabanını ayarla
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=techpro123
ENV POSTGRES_DB=techprotodo

# Postgres portunu aç
EXPOSE 5432
